const restaurants = [
  {
    id: 1,
    name: "Madero",
    color: "#67111C",
    rate: 4.9,
    category: "Lanches",
    time: "70-80 min",
    price: "R$8,00",
    km: "2km",
  },
  {
    id: 2,
    name: "Zancanaro",
    color: "#F5F749",
    rate: 4.5,
    category: "Brasileira",
    time: "50-80 min",
    price: "R$24,90",
    km: "2,3km",
  },
  {
    id: 3,
    name: "McDonalds",
    color: "#67111C",
    rate: 4.2,
    category: "Lanches",
    time: "15-30 min",
    price: "Grátis",
    km: "3,5km",
  },
  {
    id: 4,
    name: "Jeronimo",
    color: "#5F7463",
    rate: 4.5,
    category: "Lanches",
    time: "30-50 min",
    price: "R$12,00",
    km: "2,3km",
  },
  {
    id: 5,
    name: "Habib's",
    color: "#33658A",
    rate: 3.8,
    category: "Lanches",
    time: "20-30 min",
    price: "Grátis",
    km: "5,3km",
  },
  {
    id: 6,
    name: "Gorillaz",
    color: "#5A5269",
    rate: 4.8,
    category: "Lanches",
    time: "30-40 min",
    price: "R$11,90",
    km: "1,3km",
  },
];

export default restaurants;
